apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: %NAMESPACE%
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: "%IMAGE_NAME%"
        imagePullPolicy: Always
        name: test
        ports:
          - name: http
            containerPort: 8000
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
  namespace: %NAMESPACE%
spec:
  selector:
    app: test
  ports:
    - name: http
      port: 8000
      targetPort: http
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: test
  name: test
  namespace: %NAMESPACE%
spec:
  ingressClassName: nginx
  rules:
  - host: %NAMESPACE%.kube.fireto.no
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              name: http
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - %NAMESPACE%.kube.fireto.no
    secretName: app-tls-cert
